In [23]:
import numpy as np
import time

In [24]:
# Create a 1D NumPy array of 10 integers ranging from 1 to 10. 
# Create a 2D NumPy array of shape (3, 3) with integers from 1 to 9. 
# Create a 3D NumPy array with random floating-point numbers of shape (3, 5, 3).
# Display the shape, size, and datatype of each array. 
# 10 not included

In [25]:
arr1 = np.arange(1,10)
print(arr1," \nshape:",arr1.shape," Size:",arr1.size , " DataType:" , arr1.dtype)
arr2 = arr1.reshape(3,3)
print(arr2," \nshape:",arr2.shape," Size:",arr2.size , " DataType:" , arr2.dtype)
arr3 = np.random.rand(3, 5, 3)
print(arr3," \nshape:",arr3.shape," Size:",arr3.size , " DataType:" , arr3.dtype)

[1 2 3 4 5 6 7 8 9]  
shape: (9,)  Size: 9  DataType: int64
[[1 2 3]
 [4 5 6]
 [7 8 9]]  
shape: (3, 3)  Size: 9  DataType: int64
[[[0.31453523 0.24536327 0.29978631]
  [0.66787487 0.60821665 0.91939049]
  [0.97634953 0.75727876 0.6517547 ]
  [0.08702341 0.97967341 0.17398757]
  [0.36286216 0.36059063 0.81785227]]

 [[0.92504153 0.9366194  0.75302855]
  [0.91696517 0.42909501 0.87928453]
  [0.3528847  0.3752781  0.86328675]
  [0.98392538 0.70865552 0.79184065]
  [0.31201496 0.90018212 0.7548277 ]]

 [[0.01535289 0.1127162  0.41846754]
  [0.92145288 0.74969875 0.008858  ]
  [0.56144202 0.16418514 0.00750271]
  [0.17199357 0.15328684 0.13833132]
  [0.22135021 0.20135083 0.58908558]]]  
shape: (3, 5, 3)  Size: 45  DataType: float64


In [26]:
# 1. Create a NumPy array from the following list:  
#       data = [10, 20, 30, 40, 50, 60, 70, 80, 90] 
# 2. Write a Python program to:  
#       o Retrieve the first three elements of the array. 
#       o Retrieve every alternate element of the array. 
#       o Reverse the array. 
# 3. Perform the above operations and display the results. 

In [27]:
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
arr = np.array(data)
print("First three elements : ",arr[0:3])
print("Alternative elements : ", arr[::2])
print("Reversed Array : ",arr[::-1])

First three elements :  [10 20 30]
Alternative elements :  [10 30 50 70 90]
Reversed Array :  [90 80 70 60 50 40 30 20 10]


In [28]:
# Create two NumPy arrays, A and B, each with 5 random integers between 1 and 20. 
# 2. Write a Python program to:  
#       o Add, subtract, multiply, and divide the two arrays elementwise. 
#       o Compute the dot product of the arrays. 
#       o Find the mean, median, standard deviation, and variance of array A. 
#       o Identify the maximum and minimum values in array B and their indices.

In [29]:
arr1 = np.random.randint(1,20,5)
arr2 = np.random.randint(1,20,size=(5))
print(arr1," ",arr2)
print("Addition: " , arr1 + arr2)
print("Subtract: " , arr1 - arr2)
print("multiply: " , arr1 * arr2)
print("division: " , arr1 / arr2)
print("dot product : ",np.dot(arr1,arr2))

print("\nArray1")
print("Mean: " , np.mean(arr1))
print("Median: " , np.median(arr1))
print("Standard Deviation: ",np.std(arr1))
print("Variance: " , np.var(arr1))

print("\nArray2")
print("Maximum " , np.max(arr2) , " Index:", np.argmax(arr2))
print("Minimum " , np.min(arr2) , " Index:", np.argmin(arr2))

[18 10 11 11 15]   [ 6 13  6 19 18]
Addition:  [24 23 17 30 33]
Subtract:  [12 -3  5 -8 -3]
multiply:  [108 130  66 209 270]
division:  [3.         0.76923077 1.83333333 0.57894737 0.83333333]
dot product :  783

Array1
Mean:  13.0
Median:  11.0
Standard Deviation:  3.03315017762062
Variance:  9.2

Array2
Maximum  19  Index: 3
Minimum  6  Index: 0


In [30]:
# 1. Create a 1D NumPy array of 12 integers ranging from 1 to 12. 
# 2. Write a Python program to:  
#       o Reshape the array into a 2D array of shape (4, 3). 
#       o Reshape the array into a 3D array of shape (2, 2, 3). 
#       o Transpose the reshaped 2D array and display its shape. 

In [31]:
arr = np.arange(1,13)
print(arr,"\n")

arr1 = arr.reshape(4,3)
print(arr1," \nshape:",arr1.shape , "\n")

arr2 = arr.reshape(2,2,3)
print(arr2," \nshape:",arr2.shape , "\n")

arr3 = arr2.transpose()
print(arr3," \nshape:",arr3.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12] 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]  
shape: (4, 3) 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]  
shape: (2, 2, 3) 

[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]  
shape: (3, 2, 2)


In [32]:
# 1. Create a NumPy array with 15 random integers between 10 and 50. 
# 2. Write a Python program to:  
#       o Find all elements greater than 25. 
#       o Replace all elements less than 30 with 0. 
#       o Count the number of elements divisible by 5.

In [33]:
arr = np.random.randint(10,51,15)
print(arr[arr>25])

arr[arr<30]=0
print(arr)

print("divisible by 5 : " , np.sum(arr%5==0))

[26 35 26 49 32 31 40 50 34 41 44]
[ 0 35  0 49 32 31  0  0 40 50 34 41  0 44  0]
divisible by 5 :  9


In [34]:
# Use NumPy's built-in functions to:  
#       o Create an array of 10 equally spaced values between 0 and 1. 
#       o Create an identity matrix of size 4x4. 
#       o Generate a 1D array of 20 random integers between 1 and 100, sort it and find the 5 largest elements.

In [35]:
arr = np.linspace(0,1,10)
print(arr)

arr = np.eye(4)
print(arr)

arr = np.random.randint(1,101,20)
print("Array:",arr)
arr.sort()
print("Top Five elements : " ,arr[-1:-6:-1])

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Array: [84 57  8 10 51 29 16 33 38 72 37 27 96 50  9 13  3 40 68 88]
Top Five elements :  [96 88 84 72 68]


In [36]:
#  Create a Python program that:  
#       o Generates two large random arrays of size (100, 100). 
#       o Performs matrix multiplication on the two arrays. 
#       o Finds the determinant and inverse of the resulting matrix (if possible). 
#       o Measures the time taken to complete these operations.

In [37]:
#Two large random arrays
A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

# Time before doing operations
start_time = time.time()

# Matrix multiplication
print(np.matmul(A, B))

# Determinant
det = np.linalg.det(matrix_mul)
print(det)

# Inverse if determinant is not zero
if det != 0:
    inverse = np.linalg.inv(matrix_mul)
    print(inverse)
else:
    print("Inverse does not exist.")

    print("Inverse computed successfully.")

# Time when these operations are done
end_time = time.time()

# Measuring total time = end-start
total_time = end_time - start_time
print("Total time taken to perform these operations : " , total_time)

[[21.78978516 22.21448344 21.25352385 ... 25.62665571 22.90035423
  24.3926466 ]
 [25.6179012  21.2581502  23.02076774 ... 26.15284849 23.25816587
  25.33269358]
 [23.66101879 22.40193297 23.5288572  ... 25.12554705 22.31504137
  22.87260451]
 ...
 [26.04522205 23.09572105 25.0838488  ... 28.69323254 25.41995655
  24.76806286]
 [23.09794526 20.30971291 24.08685286 ... 26.54819866 22.4513845
  23.88750113]
 [24.67751532 22.47195424 24.23290022 ... 26.61683738 23.62587766
  25.23472836]]
-9.222219892962574e+49
[[ 5.64547663 -2.1621899   5.68175768 ...  7.67272122  4.43749622
   5.59375516]
 [-5.35085503  0.67685234 -5.05843552 ... -8.19478006 -3.94179995
  -4.26461896]
 [-5.61545676  2.54206597 -4.56588383 ... -6.4979039  -4.54588456
  -7.18543939]
 ...
 [12.82376129 -3.72014063 11.54936099 ... 18.79369785 10.50191388
  13.45094626]
 [-6.17543277  0.50888387 -6.57909756 ... -8.07930351 -2.99917683
  -1.85429209]
 [-3.82246342  1.30067288 -4.20792744 ... -4.28686032 -2.40366
  -2.34993305